"""empty message

Revision ID: d1c3a38f3cd8
Revises: 0e88816b7da6
Create Date: 2024-05-21 16:16:04.717690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c3a38f3cd8'
down_revision = '0e88816b7da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_sold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint('fk_orders_table_product_id_products_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_table_item_id_products_table'), 'products_table', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('products_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('item_img', sa.String(), nullable=False))
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('item_img')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('orders_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_orders_table_item_id_products_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_table_product_id_products_table', 'products_table', ['product_id'], ['id'])
        batch_op.drop_column('sold_at')
        batch_op.drop_column('price_sold')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
