"""empty message

Revision ID: d9a8f60f3521
Revises: 1e9474699b6d
Create Date: 2024-05-28 16:37:58.955434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a8f60f3521'
down_revision = '1e9474699b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_carts_table_item_id_items_table', type_='foreignkey')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_items_table_cart_id_carts_table'), 'carts_table', ['cart_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_items_table_seller_id_users_table'), 'users_table', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_table_seller_id_users_table'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_items_table_cart_id_carts_table'), type_='foreignkey')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('carts_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_carts_table_item_id_items_table', 'items_table', ['item_id'], ['id'])

    # ### end Alembic commands ###
